### ISSUE TITLE
Sort the papers 

### ISSUE THREAD

**Issue by chirag127** [daturkel/learning-papers#2]
Are these papers sorted in some order? If not I recommend sorting them by time.

**Comment by daturkel** [comment]
they are sorted alphabetically by topic. it's not ideal but i think it's slightly better than purely chronological. open to ideas though

**Comment by chirag127** [comment]
Can you please make a index or i can make a pr if you will merge it?

**Comment by daturkel** [comment]
What type of index do you have in mind?

**Comment by chirag127** [comment]
[I made](https://github.com/chirag127/learning-papers/tree/patch-1)

**Comment by daturkel** [comment]
that's great, will merge. is there a tool you used to make it automatically? (so that I can keep it up to date)
